package com.greendao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 4): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 4;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        CardNumberList2BeanDao.createTable(db, ifNotExists);
        NumCardEntityInfoDao.createTable(db, ifNotExists);
        AnimalTypeClassifyInfoDao.createTable(db, ifNotExists);
        AnimalTypeInfoDao.createTable(db, ifNotExists);
        BackGoodsReasonInfoDao.createTable(db, ifNotExists);
        EmployeeInfoDao.createTable(db, ifNotExists);
        GoodTypeInfoDao.createTable(db, ifNotExists);
        LoginInfoDao.createTable(db, ifNotExists);
        NumCardListInfoDao.createTable(db, ifNotExists);
        ServiceTypeInfoDao.createTable(db, ifNotExists);
        VipCardInfoDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        CardNumberList2BeanDao.dropTable(db, ifExists);
        NumCardEntityInfoDao.dropTable(db, ifExists);
        AnimalTypeClassifyInfoDao.dropTable(db, ifExists);
        AnimalTypeInfoDao.dropTable(db, ifExists);
        BackGoodsReasonInfoDao.dropTable(db, ifExists);
        EmployeeInfoDao.dropTable(db, ifExists);
        GoodTypeInfoDao.dropTable(db, ifExists);
        LoginInfoDao.dropTable(db, ifExists);
        NumCardListInfoDao.dropTable(db, ifExists);
        ServiceTypeInfoDao.dropTable(db, ifExists);
        VipCardInfoDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CardNumberList2BeanDao.class);
        registerDaoClass(NumCardEntityInfoDao.class);
        registerDaoClass(AnimalTypeClassifyInfoDao.class);
        registerDaoClass(AnimalTypeInfoDao.class);
        registerDaoClass(BackGoodsReasonInfoDao.class);
        registerDaoClass(EmployeeInfoDao.class);
        registerDaoClass(GoodTypeInfoDao.class);
        registerDaoClass(LoginInfoDao.class);
        registerDaoClass(NumCardListInfoDao.class);
        registerDaoClass(ServiceTypeInfoDao.class);
        registerDaoClass(VipCardInfoDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
