package com.greendao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import ys.app.pad.model.ServiceTypeInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SERVICE_TYPE_INFO".
*/
public class ServiceTypeInfoDao extends AbstractDao<ServiceTypeInfo, Long> {

    public static final String TABLENAME = "SERVICE_TYPE_INFO";

    /**
     * Properties of entity ServiceTypeInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Allcount = new Property(0, String.class, "allcount", false, "ALLCOUNT");
        public final static Property Imgurl = new Property(1, String.class, "imgurl", false, "IMGURL");
        public final static Property ShopId = new Property(2, String.class, "shopId", false, "SHOP_ID");
        public final static Property CardType = new Property(3, int.class, "cardType", false, "CARD_TYPE");
        public final static Property Count = new Property(4, String.class, "count", false, "COUNT");
        public final static Property Name = new Property(5, String.class, "name", false, "NAME");
        public final static Property Id = new Property(6, long.class, "id", true, "_id");
        public final static Property RequestTime = new Property(7, long.class, "requestTime", false, "REQUEST_TIME");
        public final static Property Discount = new Property(8, double.class, "discount", false, "DISCOUNT");
        public final static Property VipCardId = new Property(9, Long.class, "vipCardId", false, "VIP_CARD_ID");
        public final static Property ClassifyName = new Property(10, String.class, "classifyName", false, "CLASSIFY_NAME");
        public final static Property ClassifyId = new Property(11, int.class, "classifyId", false, "CLASSIFY_ID");
        public final static Property Type = new Property(12, int.class, "type", false, "TYPE");
        public final static Property CardId = new Property(13, int.class, "cardId", false, "CARD_ID");
        public final static Property Select = new Property(14, int.class, "select", false, "SELECT");
    }

    private Query<ServiceTypeInfo> vipCardInfo_CardDiscountList2Query;

    public ServiceTypeInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ServiceTypeInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SERVICE_TYPE_INFO\" (" + //
                "\"ALLCOUNT\" TEXT," + // 0: allcount
                "\"IMGURL\" TEXT," + // 1: imgurl
                "\"SHOP_ID\" TEXT," + // 2: shopId
                "\"CARD_TYPE\" INTEGER NOT NULL ," + // 3: cardType
                "\"COUNT\" TEXT," + // 4: count
                "\"NAME\" TEXT," + // 5: name
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 6: id
                "\"REQUEST_TIME\" INTEGER NOT NULL ," + // 7: requestTime
                "\"DISCOUNT\" REAL NOT NULL ," + // 8: discount
                "\"VIP_CARD_ID\" INTEGER," + // 9: vipCardId
                "\"CLASSIFY_NAME\" TEXT," + // 10: classifyName
                "\"CLASSIFY_ID\" INTEGER NOT NULL ," + // 11: classifyId
                "\"TYPE\" INTEGER NOT NULL ," + // 12: type
                "\"CARD_ID\" INTEGER NOT NULL ," + // 13: cardId
                "\"SELECT\" INTEGER NOT NULL );"); // 14: select
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SERVICE_TYPE_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ServiceTypeInfo entity) {
        stmt.clearBindings();
 
        String allcount = entity.getAllcount();
        if (allcount != null) {
            stmt.bindString(1, allcount);
        }
 
        String imgurl = entity.getImgurl();
        if (imgurl != null) {
            stmt.bindString(2, imgurl);
        }
 
        String shopId = entity.getShopId();
        if (shopId != null) {
            stmt.bindString(3, shopId);
        }
        stmt.bindLong(4, entity.getCardType());
 
        String count = entity.getCount();
        if (count != null) {
            stmt.bindString(5, count);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(6, name);
        }
        stmt.bindLong(7, entity.getId());
        stmt.bindLong(8, entity.getRequestTime());
        stmt.bindDouble(9, entity.getDiscount());
 
        Long vipCardId = entity.getVipCardId();
        if (vipCardId != null) {
            stmt.bindLong(10, vipCardId);
        }
 
        String classifyName = entity.getClassifyName();
        if (classifyName != null) {
            stmt.bindString(11, classifyName);
        }
        stmt.bindLong(12, entity.getClassifyId());
        stmt.bindLong(13, entity.getType());
        stmt.bindLong(14, entity.getCardId());
        stmt.bindLong(15, entity.getSelect());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ServiceTypeInfo entity) {
        stmt.clearBindings();
 
        String allcount = entity.getAllcount();
        if (allcount != null) {
            stmt.bindString(1, allcount);
        }
 
        String imgurl = entity.getImgurl();
        if (imgurl != null) {
            stmt.bindString(2, imgurl);
        }
 
        String shopId = entity.getShopId();
        if (shopId != null) {
            stmt.bindString(3, shopId);
        }
        stmt.bindLong(4, entity.getCardType());
 
        String count = entity.getCount();
        if (count != null) {
            stmt.bindString(5, count);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(6, name);
        }
        stmt.bindLong(7, entity.getId());
        stmt.bindLong(8, entity.getRequestTime());
        stmt.bindDouble(9, entity.getDiscount());
 
        Long vipCardId = entity.getVipCardId();
        if (vipCardId != null) {
            stmt.bindLong(10, vipCardId);
        }
 
        String classifyName = entity.getClassifyName();
        if (classifyName != null) {
            stmt.bindString(11, classifyName);
        }
        stmt.bindLong(12, entity.getClassifyId());
        stmt.bindLong(13, entity.getType());
        stmt.bindLong(14, entity.getCardId());
        stmt.bindLong(15, entity.getSelect());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 6);
    }    

    @Override
    public ServiceTypeInfo readEntity(Cursor cursor, int offset) {
        ServiceTypeInfo entity = new ServiceTypeInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // allcount
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // imgurl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // shopId
            cursor.getInt(offset + 3), // cardType
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // count
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // name
            cursor.getLong(offset + 6), // id
            cursor.getLong(offset + 7), // requestTime
            cursor.getDouble(offset + 8), // discount
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // vipCardId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // classifyName
            cursor.getInt(offset + 11), // classifyId
            cursor.getInt(offset + 12), // type
            cursor.getInt(offset + 13), // cardId
            cursor.getInt(offset + 14) // select
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ServiceTypeInfo entity, int offset) {
        entity.setAllcount(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setImgurl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setShopId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCardType(cursor.getInt(offset + 3));
        entity.setCount(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setId(cursor.getLong(offset + 6));
        entity.setRequestTime(cursor.getLong(offset + 7));
        entity.setDiscount(cursor.getDouble(offset + 8));
        entity.setVipCardId(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setClassifyName(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setClassifyId(cursor.getInt(offset + 11));
        entity.setType(cursor.getInt(offset + 12));
        entity.setCardId(cursor.getInt(offset + 13));
        entity.setSelect(cursor.getInt(offset + 14));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ServiceTypeInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ServiceTypeInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ServiceTypeInfo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "cardDiscountList2" to-many relationship of VipCardInfo. */
    public List<ServiceTypeInfo> _queryVipCardInfo_CardDiscountList2(Long vipCardId) {
        synchronized (this) {
            if (vipCardInfo_CardDiscountList2Query == null) {
                QueryBuilder<ServiceTypeInfo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.VipCardId.eq(null));
                vipCardInfo_CardDiscountList2Query = queryBuilder.build();
            }
        }
        Query<ServiceTypeInfo> query = vipCardInfo_CardDiscountList2Query.forCurrentThread();
        query.setParameter(0, vipCardId);
        return query.list();
    }

}
