package com.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import ys.app.pad.model.VipCardInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VIP_CARD_INFO".
*/
public class VipCardInfoDao extends AbstractDao<VipCardInfo, Long> {

    public static final String TABLENAME = "VIP_CARD_INFO";

    /**
     * Properties of entity VipCardInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ProductList = new Property(0, String.class, "productList", false, "PRODUCT_LIST");
        public final static Property ProductNum = new Property(1, String.class, "productNum", false, "PRODUCT_NUM");
        public final static Property CommodityList = new Property(2, String.class, "commodityList", false, "COMMODITY_LIST");
        public final static Property CommodityNum = new Property(3, String.class, "commodityNum", false, "COMMODITY_NUM");
        public final static Property ShopId = new Property(4, String.class, "shopId", false, "SHOP_ID");
        public final static Property ExpiryDate = new Property(5, int.class, "expiryDate", false, "EXPIRY_DATE");
        public final static Property CommodityDiscount = new Property(6, double.class, "commodityDiscount", false, "COMMODITY_DISCOUNT");
        public final static Property ProductDiscount = new Property(7, double.class, "productDiscount", false, "PRODUCT_DISCOUNT");
        public final static Property Name = new Property(8, String.class, "name", false, "NAME");
        public final static Property Id = new Property(9, long.class, "id", true, "_id");
        public final static Property Info = new Property(10, String.class, "info", false, "INFO");
        public final static Property RequestTime = new Property(11, long.class, "requestTime", false, "REQUEST_TIME");
        public final static Property State = new Property(12, int.class, "state", false, "STATE");
        public final static Property Classification = new Property(13, int.class, "classification", false, "CLASSIFICATION");
        public final static Property Expand = new Property(14, boolean.class, "expand", false, "EXPAND");
        public final static Property IsClick = new Property(15, int.class, "isClick", false, "IS_CLICK");
    }

    private DaoSession daoSession;


    public VipCardInfoDao(DaoConfig config) {
        super(config);
    }
    
    public VipCardInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VIP_CARD_INFO\" (" + //
                "\"PRODUCT_LIST\" TEXT," + // 0: productList
                "\"PRODUCT_NUM\" TEXT," + // 1: productNum
                "\"COMMODITY_LIST\" TEXT," + // 2: commodityList
                "\"COMMODITY_NUM\" TEXT," + // 3: commodityNum
                "\"SHOP_ID\" TEXT," + // 4: shopId
                "\"EXPIRY_DATE\" INTEGER NOT NULL ," + // 5: expiryDate
                "\"COMMODITY_DISCOUNT\" REAL NOT NULL ," + // 6: commodityDiscount
                "\"PRODUCT_DISCOUNT\" REAL NOT NULL ," + // 7: productDiscount
                "\"NAME\" TEXT," + // 8: name
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 9: id
                "\"INFO\" TEXT," + // 10: info
                "\"REQUEST_TIME\" INTEGER NOT NULL ," + // 11: requestTime
                "\"STATE\" INTEGER NOT NULL ," + // 12: state
                "\"CLASSIFICATION\" INTEGER NOT NULL ," + // 13: classification
                "\"EXPAND\" INTEGER NOT NULL ," + // 14: expand
                "\"IS_CLICK\" INTEGER NOT NULL );"); // 15: isClick
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VIP_CARD_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VipCardInfo entity) {
        stmt.clearBindings();
 
        String productList = entity.getProductList();
        if (productList != null) {
            stmt.bindString(1, productList);
        }
 
        String productNum = entity.getProductNum();
        if (productNum != null) {
            stmt.bindString(2, productNum);
        }
 
        String commodityList = entity.getCommodityList();
        if (commodityList != null) {
            stmt.bindString(3, commodityList);
        }
 
        String commodityNum = entity.getCommodityNum();
        if (commodityNum != null) {
            stmt.bindString(4, commodityNum);
        }
 
        String shopId = entity.getShopId();
        if (shopId != null) {
            stmt.bindString(5, shopId);
        }
        stmt.bindLong(6, entity.getExpiryDate());
        stmt.bindDouble(7, entity.getCommodityDiscount());
        stmt.bindDouble(8, entity.getProductDiscount());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(9, name);
        }
        stmt.bindLong(10, entity.getId());
 
        String info = entity.getInfo();
        if (info != null) {
            stmt.bindString(11, info);
        }
        stmt.bindLong(12, entity.getRequestTime());
        stmt.bindLong(13, entity.getState());
        stmt.bindLong(14, entity.getClassification());
        stmt.bindLong(15, entity.getExpand() ? 1L: 0L);
        stmt.bindLong(16, entity.getIsClick());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VipCardInfo entity) {
        stmt.clearBindings();
 
        String productList = entity.getProductList();
        if (productList != null) {
            stmt.bindString(1, productList);
        }
 
        String productNum = entity.getProductNum();
        if (productNum != null) {
            stmt.bindString(2, productNum);
        }
 
        String commodityList = entity.getCommodityList();
        if (commodityList != null) {
            stmt.bindString(3, commodityList);
        }
 
        String commodityNum = entity.getCommodityNum();
        if (commodityNum != null) {
            stmt.bindString(4, commodityNum);
        }
 
        String shopId = entity.getShopId();
        if (shopId != null) {
            stmt.bindString(5, shopId);
        }
        stmt.bindLong(6, entity.getExpiryDate());
        stmt.bindDouble(7, entity.getCommodityDiscount());
        stmt.bindDouble(8, entity.getProductDiscount());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(9, name);
        }
        stmt.bindLong(10, entity.getId());
 
        String info = entity.getInfo();
        if (info != null) {
            stmt.bindString(11, info);
        }
        stmt.bindLong(12, entity.getRequestTime());
        stmt.bindLong(13, entity.getState());
        stmt.bindLong(14, entity.getClassification());
        stmt.bindLong(15, entity.getExpand() ? 1L: 0L);
        stmt.bindLong(16, entity.getIsClick());
    }

    @Override
    protected final void attachEntity(VipCardInfo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 9);
    }    

    @Override
    public VipCardInfo readEntity(Cursor cursor, int offset) {
        VipCardInfo entity = new VipCardInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // productList
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // productNum
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // commodityList
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // commodityNum
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // shopId
            cursor.getInt(offset + 5), // expiryDate
            cursor.getDouble(offset + 6), // commodityDiscount
            cursor.getDouble(offset + 7), // productDiscount
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // name
            cursor.getLong(offset + 9), // id
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // info
            cursor.getLong(offset + 11), // requestTime
            cursor.getInt(offset + 12), // state
            cursor.getInt(offset + 13), // classification
            cursor.getShort(offset + 14) != 0, // expand
            cursor.getInt(offset + 15) // isClick
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VipCardInfo entity, int offset) {
        entity.setProductList(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setProductNum(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCommodityList(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCommodityNum(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setShopId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setExpiryDate(cursor.getInt(offset + 5));
        entity.setCommodityDiscount(cursor.getDouble(offset + 6));
        entity.setProductDiscount(cursor.getDouble(offset + 7));
        entity.setName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setId(cursor.getLong(offset + 9));
        entity.setInfo(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setRequestTime(cursor.getLong(offset + 11));
        entity.setState(cursor.getInt(offset + 12));
        entity.setClassification(cursor.getInt(offset + 13));
        entity.setExpand(cursor.getShort(offset + 14) != 0);
        entity.setIsClick(cursor.getInt(offset + 15));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VipCardInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VipCardInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VipCardInfo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
